
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 18 00:30:17 CEST 2025
//----------------------------------------------------

package org.example;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 17;
  public static final int ELSE = 21;
  public static final int PLUS = 10;
  public static final int THEN = 20;
  public static final int CHAR = 14;
  public static final int SEMI = 5;
  public static final int LEFTPAR = 3;
  public static final int STAR = 11;
  public static final int END = 16;
  public static final int IF = 19;
  public static final int RIGHTPAR = 4;
  public static final int COLON = 7;
  public static final int ID = 22;
  public static final int WRITE = 18;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 15;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int CONST = 23;
  public static final int error = 1;
  public static final int DOT = 6;
  public static final int ASSIGN = 9;
  public static final int INTEGER = 13;
  public static final int VAR = 12;
}

